import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { PageJavaScript } from '@/components/PageJavaScript'
import { Stylesheet } from '@/components/Stylesheet'

const createAccount = () => {
  return (
    <>
     <PageJavaScript></PageJavaScript>
      <Head>
        <title>Create Account - Jobfid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/page_images/fevicon.png" />
       
        <Stylesheet></Stylesheet>
      </Head>
      <section>
     <center>
        <div class="container">
    <div class="col-lg-5">
        <div class="card shadow px-4 py-5">
            
            <h1 class="mb-2 h4">Create New Account</h1>
            <p class="mb-0">Already Have account?<a href="/auth/login"> Login</a></p>

            <form class="mt-4 text-start">
            <div class="mb-3">
                    <div class="form-icon">
                        <input type="text" class="form-control form-control-icon" name="username" id="iconInput" value="" placeholder="Enter Fullname"/>
                        <i class="fa fa-user text-black"></i>
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-icon">
                        <input type="text" class="form-control form-control-icon" name="username" id="iconInput" value="" placeholder="Enter Email"/>
                        <i class="fa fa-envelope text-black"></i>
                    </div>
                </div>
                <div class="mb-3">
                <div class="input-group">
                    <button class=" language-toggler btn btn-primary-soft border" type="button"><img src='/images/page_images/bn.png'/><span class="ms-1">+ 88</span></button>
                    <input type="text" class="form-control rounded-end flag-input" minlength="11" maxlength="11" v-model="form.mobile" placeholder="Enter number" />
                                        
                    </div>
                </div>
               
                
                <div class="mb-3 position-relative">
                    <div class="form-icon">
                        <input type="password" class="form-control form-control-icon" name="password" id="iconInput" placeholder="Enter Password"/>
                        <i class="fa fa-key text-black"></i>
                        <span class="position-absolute top-0 end-15 translate-middle-y p-0 mt-3">
                            <i class="fakepasswordicon fas fa-eye-slash cursor-pointer p-2"></i>
                        </span>
                </div>
                
                   
                </div>
                <div class="mb-3 position-relative">
                    <div class="form-icon">
                        <input type="password" class="form-control form-control-icon" name="password" id="iconInput" placeholder="Enter Confirm Password"/>
                        <i class="fa fa-key text-black"></i>
                        <span class="position-absolute top-0 end-15 translate-middle-y p-0 mt-3">
                            <i class="fakepasswordicon fas fa-eye-slash cursor-pointer p-2"></i>
                        </span>
                </div>
                
                   
                </div>
                <div class="mb-3">
                    
                        <input type="checkbox" class="form-check-input me-2"/>
                        <label class="form-check-label" for="rememberCheck"><p class="mb-0 fs-16 text-black fst-italic">By registering you agree to the <a href="#" class="text-primary text-decoration-underline fst-normal fw-medium">Terms of Use</a></p></label>
                </div>
                <div><button type="submit" class="btn btn-success w-100 mb-0">Register</button></div>

                
                <div class="position-relative my-4">
                    <hr/>
                    <p class="small bg-mode position-absolute top-50 start-50 translate-middle px-2">Or sign in with</p>
                </div>

                <div class="vstack gap-3">
                    <a href="#" class="btn btn-light mb-0"><i class="fab fa-fw fa-google text-google-icon me-2"></i>Sign in with Google</a>
                </div>

            </form>
        </div>		
    </div>
    </div>
    </center>
    </section>
    </>
  )
}

export default createAccount