import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Stylesheet } from '@/components/Stylesheet'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ATS Technology - Broadband Internet Service Provider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Stylesheet></Stylesheet>
      </Head>
     
      <div className="section rev_slider_wrapper ">
    
    <div id="navigation-swiper" className="swiper rounded">
        <div className="swiper-wrapper">
            <div className="swiper-slide">
                <img src="/images/bg1.png" alt="" className="img-fluid" />
            </div>
            <div className="swiper-slide">
                <img src="/images/bg2.png" alt="" className="img-fluid" />
            </div>
            
        </div>
        <div id="swiper-button-next"></div>
        <div id="swiper-button-prev"></div>
        <div id="swiper-pagination"></div>
    </div>
    
</div>
<div className="section padding_layout_1">
    <div className="container">
        <div className="row">
            <div className="col-md-12">
                <div className="full">
                    <div className="main_heading text_align_center">
                        <h2>Looking For a new Internet Connection?</h2>
                        <p className="large">Here are some of our most popular packages</p>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div className="row" >
                <div className="col-lg-2 col-md-6 col-sm-6 col-xs-12 price_table_active margin_bottom_30">
                    <div className="row">
                        <div className="price_table_inner">
                            <div className="price_head text_align_center white_fonts">
                                <h5>Lightning</h5>
                            </div>
                            <div className="price_contant">
                                <div className="center">
                                    <p className="price_amount"><span className="price_no">15</span> Mbps</p>
                                </div>
                                <div className="price_cont text_align_center">
                                    <p><i className="fa fa-check" ></i> Unlimited IX</p>
                                    <p><i className="fa fa-check" ></i> 4K Youtube & Facebook Streaming</p>
                                    <p><i className="fa fa-check" ></i> Private IP</p>
                                    <p><i className="fa fa-check" ></i> FTTH Connectivity</p>
                                </div>
                                
                            </div>
                            <div className="center">
                                <p className="price_amount">৳<span className="price_no_2"> 800</span>/Month</p>
                            </div>
                            <div className="price_bottom">
                                <div className="center"> <a href="online-registration" className="btn main_bt">Get Now!</a> </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                <div className="col-lg-2 col-md-6 col-sm-6 col-xs-12 price_table_active margin_bottom_30">
                    <div className="row">
                        <div className="price_table_inner">
                            <div className="price_head text_align_center white_fonts">
                                <h5>Storm</h5>
                            </div>
                            <div className="price_contant">
                                <div className="center">
                                    <p className="price_amount"><span className="price_no">20</span> Mbps</p>
                                </div>
                                <div className="price_cont text_align_center">
                                    <p><i className="fa fa-check" ></i> Unlimited IX</p>
                                    <p><i className="fa fa-check" ></i> 4K Youtube & Facebook Streaming</p>
                                    <p><i className="fa fa-check" ></i> Public IP</p>
                                    <p><i className="fa fa-check" ></i> FTTH Connectivity</p>
                                </div>
                                
                            </div>
                            <div className="center">
                                <p className="price_amount">৳<span className="price_no_2"> 1000</span>/Month</p>
                            </div>
                            <div className="price_bottom">
                                <div className="center"> <a href="online-registration" className="btn main_bt">Get Now!</a> </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-2 col-md-6 col-sm-6 col-xs-12 price_table_active margin_bottom_30">
                    <div className="row">
                        <div className="price_table_inner">
                            <div className="price_head text_align_center white_fonts">
                                <h5>Tornado</h5>
                            </div>
                            <div className="price_contant">
                                <div className="center">
                                    <p className="price_amount"><span className="price_no">30</span> Mbps</p>
                                </div>
                                <div className="price_cont text_align_center">
                                    <p><i className="fa fa-check" ></i> Unlimited IX</p>
                                    <p><i className="fa fa-check" ></i> 4K Youtube & Facebook Streaming</p>
                                    <p><i className="fa fa-check" ></i> Public IP</p>
                                    <p><i className="fa fa-check" ></i> FTTH Connectivity</p>
                                </div>
                                
                            </div>
                            <div className="center">
                                <p className="price_amount">৳<span className="price_no_2"> 1500</span>/Month</p>
                            </div>
                            <div className="price_bottom">
                                <div className="center"> <a href="online-registration" className="btn main_bt">Get Now!</a> </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-2 col-md-6 col-sm-6 col-xs-12 price_table_active margin_bottom_30" >
                    <div className="row">
                        <div className="price_table_inner">
                            <div className="price_head text_align_center white_fonts">
                                <h5>Typhoon</h5>
                            </div>
                            <div className="price_contant">
                                <div className="center">
                                    <p className="price_amount"><span className="price_no">40</span> Mbps</p>
                                </div>
                                <div className="price_cont text_align_center">
                                    <p><i className="fa fa-check" ></i> Unlimited IX</p>
                                    <p><i className="fa fa-check" ></i> 4K Youtube & Facebook Streaming</p>
                                    <p><i className="fa fa-check" ></i> Public IP</p>
                                    <p><i className="fa fa-check" ></i> FTTH Connectivity</p>
                                </div>
                                
                            </div>
                            <div className="center">
                                <p className="price_amount">৳<span className="price_no_2"> 2000</span>/Month</p>
                            </div>
                            <div className="price_bottom">
                                <div className="center"> <a href="online-registration" className="btn main_bt">Get Now!</a> </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="row ">
            <div className="col-md-8">
                <div className="full margin_bottom_30">
                    <div className="accordion border_circle">
                        <div className="bs-example">
                            <div className="panel-group" id="accordion">
                                <div className="panel panel-default">
                                    <div className="panel-heading">
                                        <p className="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><i className="fa fa-check" aria-hidden="true"></i> Multiple Upstream<i className="fa fa-angle-down"></i></a> </p>
                                    </div>
                                    <div id="collapseOne" className="panel-collapse collapse in">
                                        <div className="panel-body">
                                            <p>We are connected with multiple upstreams. So, there is almost no downtime. We optimize our routes in best paths so you can get better speed.</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="panel panel-default">
                                    <div className="panel-heading">
                                        <p className="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><i className="fa fa-check"></i> IPv4 & IPv6 Available<i className="fa fa-angle-down"></i></a> </p>
                                    </div>
                                    <div id="collapseTwo" className="panel-collapse collapse">
                                        <div className="panel-body">
                                            <p>We are providing Public IP to our users. And We are also IPv6 Ready.</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="panel panel-default">
                                    <div className="panel-heading">
                                        <p className="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><i className="fa fa-check"></i> Upto 100 Mbps VAS Speed<i className="fa fa-angle-down"></i></a> </p>
                                    </div>
                                    <div id="collapseThree" className="panel-collapse collapse">
                                        <div className="panel-body">
                                            <p>Enjoy Upto 100 Mbps speed on Youtube, Facebook, BDIX, Steam, origin and many more.</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="panel panel-default">
                                    <div className="panel-heading">
                                        <p className="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><i className="fa fa-check" aria-hidden="true"></i> Low Latency & Optimized Ping<i className="fa fa-angle-down"></i></a> </p>
                                    </div>
                                    <div id="collapseFour" className="panel-collapse collapse in">
                                        <div className="panel-body">
                                            <p>We are working hard for our gamers. We are optimizing latency in every possible way to provide smooth gaming performance.</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="panel panel-default">
                                    <div className="panel-heading">
                                        <p className="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><i className="fa fa-check" aria-hidden="true"></i> FTTH & Underground Connectivity<i className="fa fa-angle-down"></i></a> </p>
                                    </div>
                                    <div id="collapseFive" className="panel-collapse collapse in">
                                        <div className="panel-body">
                                            <p>We are providing connection via optical Fiber Technology.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="col-md-4">
                <div className="full" >
                    <h2>Want a new connection?</h2>
                    <p>Don't worry we have got you Covered!</p>
                    <p><a className="btn main_bt" href="coverage-area"><i className="fa fa-map-marker"> </i> Check Coverage</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div className="section product_list_main " >
    <div className="container margin_bottom_30">
        <div className="row">
            <div className="col-md-12">
                <div className="swiper responsive-swiper rounded gallery-light margin_bottom_30">
                    <div className="swiper-wrapper">
                        <div className="swiper-slide">
                            <div className="product_list">
                                <div className="product_img"> <img className="img-responsive" src="{{ asset('images/netis-n3.jpg') }}" alt=""/> </div>
                                <div className="product_detail_btm">
                                    <div className="center">
                                        <h4><a href="it_shop_detail.html">Netis N3</a></h4>
                                    </div>
                                    
                                    <div className="product_price">
                                        <p><span className="old_price">৳ 2500</span><span className="new_price">৳ 2400</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="swiper-slide">
                            <div className="product_list">
                                <div className="product_img"> <img className="img-responsive" src="{{ asset('images/netis-wf2409e.jpg') }}" alt=""/> </div>
                                <div className="product_detail_btm">
                                    <div className="center">
                                        <h4><a href="it_shop_detail.html">Netis N3D</a></h4>
                                    </div>
                                    
                                    <div className="product_price">
                                        <p><span className="old_price">৳ 2500</span><span className="new_price">৳ 2400</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="swiper-slide">
                            <div className="product_list">
                                <div className="product_img"> <img className="img-responsive" src="{{ asset('images/utp.jpg') }}" alt=""/> </div>
                                <div className="product_detail_btm">
                                    <div className="center">
                                        <h4><a href="it_shop_detail.html">Netis N3D</a></h4>
                                    </div>
                                    
                                    <div className="product_price">
                                        <p><span className="old_price">৳ 2500</span><span className="new_price">৳ 2400</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>  
      
    </>
  )
}
